### PR TITLE
separate worker for db migrate

### PR DESCRIPTION
**Pull request by nusnewob**

### CODE REVIEW

**Comment by uktitools** [comment]
Can one of the admins verify this patch?

**Comment by canni** [comment]
Not needed anymore...

**Comment by Singletoned** [comment]
Why isn't this needed anymore?  We want the migrations to be run on a separate worker.

**Comment by canni** [comment]
It'll be useful if we could leverage it on `flynn` somehow, otherwise it'll just hang as unused `Procfile` entry for no apparent reason

**Pull request closed without merging**
