### PR TITLE
Fix bug when adding new metadata items via admin

### PR DESCRIPTION
**Pull request by reupen**
Was due to missing default value for id in BaseConstantModel.

Also makes the metadata admin forms more consistent, and adds export experience categories to admin.

### CODE REVIEW

**Comment by marcofucci** [comment]
I think we have a huge problem with metadata.

We are using metadata in many ways but in particular:
- teams, team roles etc.: these are OK to be changed via django admin
- constants (e.g. business types etc.): which should not be allowed to be changed via the admin

At the moment we allow everyone with admin access to change anything which is very dangerous and we need to be careful as this might come back as a boomerang and cause much pain.

I don't think it's a good idea to have all metadata in the admin but only the ones we think it's safe to be changed.

**Comment by reupen** [comment]
Isn't that a permissions problem though?

**Comment by marcofucci** [comment]
No I don't think it's a permission problem, constants should not be in the admin area, they should only be in the code.
If you allow constants to be changed via the admin there will always be a misalignment between the fixtures and the actual database.

If you think it's a permission thing, we should change all the fixtures to be initial_fixtures instead of metadata and we need to solve the problem of our environments being completely different from production.

**Comment by elcct** [comment]
But wouldn't that be a different PR?

**Comment by marcofucci** [comment]
yes but why we don't remove things from the admin in the first place instead of fixing it? It seems a bit pointless, no?

**Comment by elcct** [comment]
I think the requirement was to enable admin user to disable/enable referential data in the admin, if we remove that from the admin then we will remove that ability.

**Comment by marcofucci** [comment]
Yeah that's exactly what I say, we allow some and disallow other :)

**Comment by elcct** [comment]
We needed to enable that feature for all referential data in the admin.

**Comment by reupen** [comment]
The specific problem encountered was that you can't add a team via admin. And it just happened to affect all the metadata models.

And even if you shouldn't be able to add, delete or edit some of them, I don't see why it follows that you should be able to see a list of them. And fixtures isn't a good way of maintaining data, those probably should've been loaded via a migration.

Anyway changing that would be a bigger piece of work, this is a simple fix for not being able to add a team.

**Comment by reupen** [comment]
@marcofucci @elcct Updated this to make the read-only code for CH companies more reusable, and applied it to business types, investment project stages and investment types.

**Comment by marcofucci** [comment]
💯

**Pull request merged**
