### PR TITLE
Update fixtures from prod values

### PR DESCRIPTION
**Pull request by marcofucci**
This updates the fixtures from the prod env:
- sectors: new records have been added
- services: new records have been added
- interactions: the following interaction types have been deleted:
	- Fax
	- Telex
	- UKTI Website
	- SMS
	- Business Card

Please check the files as I'm not sure if this is what we want.
Also, as some interaction types have been deleted, you'll need to delete old records:

```
echo "from datahub.metadata.models import InteractionType; InteractionType.objects.filter(id__in=('71c226d7-5d95-e211-a939-e4115bead28a', '73c226d7-5d95-e211-a939-e4115bead28a', '75c226d7-5d95-e211-a939-e4115bead28a', 'a4d71fdd-5d95-e211-a939-e4115bead28a', 'a6d71fdd-5d95-e211-a939-e4115bead28a')).delete()" | ./manage.py shell
```

### CODE REVIEW

**Comment by reupen** [comment]
Looks like a couple of the tests need updating.

**Comment by marcofucci** [comment]
@jim68000 can you have a look please?

**Comment by jim68000** [comment]
Data looks good

**Comment by yadmaster** [comment]
The values that have been removed are used by data in the migration. These will now fail to migrate. We need some kind of change control around LOVs as they are as much a part of the target structure as the field definitions. Once we have mapped corresponding values they cannot simply be removed without an impact analysis, The fact that a value may not be required going forwards does not mean it is not required by historic data.

**Comment by marcofucci** [comment]
@yadmaster I completely agree. 
This was just to align what we have in production at the moment with our code and it was not part of my work.

Could you please double check what interaction types are needed?

**Pull request merged**
