### PR TITLE
Initial proposal for concurrent migrations problem on flynn

### PR DESCRIPTION
**Pull request by canni**

### CODE REVIEW

**Comment by uktitools** [comment]
Can one of the admins verify this patch?

**Comment by sdonk** [comment]
Tests? If it's even possible to test this thing

**Comment by canni** [comment]
@sdonk Deployment to `flynn-staging` is a test for that ;)

**Comment by sdonk** [comment]
@canni can you exclude that python file from coverage then? So the % doesn't get affected.

**Comment by Singletoned** [comment]
If it's not testable then it's not a good solution, particularly as (IIUC) the migrations not happening at the same time is reasonably important.  That it works once or twice on staging doesn't really tell us anything, particularly as (IIUC) the migrations sometimes pass anyway.

**Comment by Singletoned** [comment]
Also, we will at the minimum need a regression test to tell us whether it is still working in 6 months time.

**Pull request merged**
