### PR TITLE
Update Python to version 3.7.2 🎉

### PR DESCRIPTION
**Pull request by reupen**
### Description of change

Release notes: https://docs.python.org/3/whatsnew/3.7.html

### Checklist

* [x] Has a new newsfragment been created? Check [changelog/README.rst](https://github.com/uktrade/data-hub-leeloo/blob/master/changelog/README.rst) for instructions
* [ ] Have any relevant search models been updated?
* [ ] Have any relevant fixtures (`fixtures/test_data.yaml`) been updated?
* [ ] Have any relevant select-/prefetch-related field lists in the views and search apps been updated?
* [ ] Has the admin site been updated (for new models, fields etc.)?
* [x] Has the README been updated (if needed)?

### CODE REVIEW

**Comment by reupen** [comment]
I suppose we should really say something in the native installation section in the README about how to get Python 3.7. Should we cover using [pyenv](https://github.com/pyenv/pyenv)? @marcofucci @elcct you also use native installations, what do you think?

**Comment by reupen** [comment]
I found using pyenv a bit too complicated, actually. I think I'll just add a generic step giving a few options without going into detail.

**Comment by marcofucci** [comment]
@reupen if you want to add something for mac just point it to https://docs.python-guide.org/starting/install3/osx/

**Comment by reupen** [comment]
Thanks @marcofucci, that's a useful guide – just pushed a couple of updates to the README.

**Pull request merged**
