### PR TITLE
Add new service types for SPI.

### PR DESCRIPTION
**Pull request by elcct**
Issue number: DH-1594 DH-1597

### Description of change

This adds two new Service Types for Service Performance Indicators (SPIs).

### Checklist

* [x] Have any relevant search models been updated?
* [x] Have any relevant fixtures (`fixtures/test_data.yaml`) been updated?
* [x] Have any relevant select-/prefetch-related field lists in the views and search apps been updated?
* [x] Has the admin site been updated (for new models, fields etc.)?
* [x] Has the README been updated (if needed)?

### CODE REVIEW

**Comment by reupen** [comment]
Isn't this something that the Live Services team should do via the admin site?

**Comment by elcct** [comment]
@reupen my next task is to create a command that builds a report using one of the service types in this PR.  It would be difficult to manage possibily different Ids or names of the services if that was created via the admin site.

**Comment by reupen** [comment]
Not sure using the service IDs is the best way to do that. We might want a new column in the service model so that we can flag the relevant services as being relevant to the report.

**Comment by elcct** [comment]
I see. Adding a column just for one particular record doesn't sound good to me, could end up having a flag for each service? ID could be set as env variable and read by the command. Then indeed this PR wouldn't be needed.

**Pull request closed without merging**
