### PR TITLE
Squash interaction and metadata migrations

### PR DESCRIPTION
**Pull request by reupen**
Issue number: N/A

### Description of change

Squashes interaction migrations up to 0019, and metadata migrations up to 0011.

There were circular dependencies again arising from the original migrations (which were difficult to resolve). I've resolved them in a similar way to the previous PR. Will leave the squashing at this for now so that we can deploy these to all environments.

### Checklist

* [x] Have any relevant search models been updated?
* [x] Have any relevant fixtures (`fixtures/test_data.yaml`) been updated?
* [x] Have any relevant select-/prefetch-related field lists in the views and search apps been updated?
* [x] Has the admin site been updated (for new models, fields etc.)?
* [x] Has the README been updated (if needed)?

### CODE REVIEW

**Comment by marcofucci** [comment]
@reupen shouldn't you keep the old migrations untouched?

**Comment by reupen** [comment]
@marcofucci Yes, but I don't have another way to resolve the circular dependencies because they're (weirdly) coming from the old migrations. Do you have any other suggestions? I don't think it's a big deal anyway, they aren't recent and we're just going to delete them after the squashing is complete.

**Comment by reupen** [comment]
Not sure why but the UAT environment was unhappy with this. Going to park this until #825 has been transitioned to a normal migration.

**Comment by reupen** [comment]
Ah, nope, it failed because the the wrong commit was deployed. So all looks fine.

**Pull request merged**
