### PR TITLE
Changes plural entity name to results in the response of basic search.

### PR DESCRIPTION
**Pull request by elcct**

### CODE REVIEW

**Comment by elcct** [comment]
Good point as it is no longer needed :) Thanks!

**Comment by reupen** [comment]
Can we do it in a backwards compatible way? Like temporarily including both properties until the front-end change is made and released?

**Comment by marcofucci** [comment]
Very good point, yes that sounds like a good idea. @elcct you would have to revert back to the previous commit, sorry about that.

**Comment by elcct** [comment]
@marcofucci @reupen @tyom said that front end is already compatible with this change

**Comment by reupen** [comment]
So if we deployed this to production today, nothing would break?

**Comment by tyom** [comment]
@reupen Nothing should break but obviously we need to test it before deploying :)

**Pull request merged**
